### ISSUE TITLE
Xdrip support

### ISSUE THREAD

**Issue by tildesley82** [pachi81/GlucoDataHandler#126]
Hi, what is required to pull numbers/data from xDrip? I have xDrip setup with local broadcast on, but aren't seeing the results, do I need to use Tasker?

**Comment by pachi81** [comment]
Please have a look here:
https://github.com/pachi81/GlucoDataHandler/blob/master/INSTALLATION.md#configure-xdrip

**Comment by tildesley82** [comment]
> Please have a look here: https://github.com/pachi81/GlucoDataHandler/blob/master/INSTALLATION.md#configure-xdrip

Thank you, thought I saw when I first installed, apologies for the easy question.

**Comment by pachi81** [comment]
No problem ;-)
