### ISSUE TITLE
Display mmol glucose values with two decimal digits

### ISSUE THREAD

**Issue by infossk** [pachi81/GlucoDataHandler#138]
It would be useful to display both blood glucose and delta in mmol to two decimal places.  Or give it an option as a parameter in the settings.  We use FSL3 with readings at 1 minute intervals.  I would see a change in trend.

![Screenshot_20240226-005131.png](https://github.com/pachi81/GlucoDataHandler/assets/8257881/c4b2ea83-4cb0-4879-ae92-73868a760c6b)

**Comment by pachi81** [comment]
It is common to have only 1 decimal digit.
I also use mmol/l and have never seen the two decimal places, yet. Only for small delta values and this is already provided by my app.
I also do not really see an advantage for that.

If I see for example 4,9 with delta -0.06, I know, that there was a small change.

I will not change it.
