### ISSUE TITLE
App is not backed up via adb backup

### ISSUE THREAD

**Issue by sgmoore** [pachi81/GlucoDataHandler#151]
Any ideas?

Adb command I'm using is  `adb backup -apk -shared -all -f ./backup.ab`

Phone is running Android 13

**Comment by pachi81** [comment]
Hi, I have not tried, yet. So no real idea.

**Comment by pachi81** [comment]
Thank you for the information. 
I just thinking about, add an Im- and Export for the settings, so you can backup the data.
It is on my list, maybe not in the next version...
