### ISSUE TITLE
App disconnecting and 'Battery optimizer is enabled' pixel 8 pro

### ISSUE THREAD

**Issue by ComptonaPrime** [pachi81/GlucoDataHandler#166]
Hey, great app!

The app keeps disconnecting from librelinkup up (not updating) even when forcing a new connection. Not sure if it's linked too battery optimisation is enabled. Although the app (watch and phone) has no restrictions

Kind regards
Andy
![Screenshot_20240810-212839](https://github.com/user-attachments/assets/b02ecace-adb7-46fc-ab23-9c24af4c3057)
![Screenshot_20240810-212830](https://github.com/user-attachments/assets/eeed1ed4-1b64-4d85-8e18-2bd42abf7df3)
![Screenshot_20240810-212814](https://github.com/user-attachments/assets/c6794379-7d4f-4760-b238-06a52bc6562f)

**Comment by pachi81** [comment]
Have you tried to disable battery optimization?
I still had another one with two phones, on the one everything was fine, even with battery optimzation and on the other one he needs to disable it.
Not sure if it was a Pixel 8 Pro.

**Comment by ComptonaPrime** [comment]
Battery optimisation is disabled, but coincidentally since the latest security update for pixel, I've had zero issues.

App still says that battery optimisation is on (it isn't) but been faultless

**Comment by ComptonaPrime** [comment]
Issue no longer present
