### ISSUE TITLE
Every minute syncing 

### ISSUE THREAD

**Issue by Krazee78** [pachi81/GlucoDataHandler#169]
I use Nightscout as source. Sometimes the app  synchronizes every minute, sometimes every 2 minutes, sometimes every 4 minutes etc. No battery optimization and things disturbing synchronization, the app can do all. But no stable every minute syncing, can you test and fix it please?

**Comment by pachi81** [comment]
Can you save the logs and send them to my mail using the contact option in GlucoDataHandler

**Comment by pachi81** [comment]
Close as it seems to be a problem with Realm mobile.
