### ISSUE TITLE
bigger floating widget dimension

### ISSUE THREAD

**Issue by ghino18** [pachi81/GlucoDataHandler#171]
hi, it is not really an issue but i ask if it is possibile to have big dimension.
now it arrive to 10, i ask  if it is possible to triple until 30.
best regards

**Comment by pachi81** [comment]
This is how it look like with 30:
![image](https://github.com/user-attachments/assets/1634602d-75a8-4f24-bf04-b3310792cd41)

And this with 20:
![image](https://github.com/user-attachments/assets/d8945545-28b4-457e-9602-d719df810403)

**Comment by pachi81** [comment]
I think 20 is enough. What do you think?

**Comment by ghino18** [comment]
I used it on a android Watch and i have to try with Its screen to be bigger as possible to be and all screen. If 30 Is not a problem to inser i would like try , i have more choice

**Comment by pachi81** [comment]
Ok, thank you for the feedback.
As you can see, it is not a problem, but I have to check the slider, as it has a lot of steps, now.
So to set the setting is a little bit more complicated.

**Comment by pachi81** [comment]
@ghino18 just a question, what size are you using, now?
