### ISSUE TITLE
Req.: send data do LibreLinkUp

### ISSUE THREAD

**Issue by oblus** [pachi81/GlucoDataHandler#173]
Hi

Can You provide functionality to send recieved glucose readings to LibreLinkUp cloud?

Tom

My setup:
OnePlus Watch 2 with juggluco as Libre 2 reader -> gdh (wear) -> android phone (S10e) -> gdh -> xdrip+

**Comment by oblus** [comment]
Too many connections killing my Watch and Phone batteries.... therefore in my setup better way should be to upload to LibreView by phone app rather than watch app.

**Comment by pachi81** [comment]
Juggluco is doing it package wise, not immediatly, so it Juggluco has really less battery usage on phone, even if you have connected your sensor to watch. 
So I think, this is the only possibility at the moment. I really not want to do it, as I do not want Abbott draw anger upon me ;-)

**Comment by oblus** [comment]
Yeah... everybody is afraid of the Abbott ??! 
And Im angry for Abbott! They should be voted to Stasburg they get money for faulty sensors but they stop develop their app !! Do I want this workarounds?? NO !!! They should make WearOs and other sw to work with Libre !!! They should give their patients clear long history review with treatment support !

Abbott is a MOB !

but I understand your position in this matter..

**Comment by oblus** [comment]
> so it Juggluco has really less battery usage on phone, even if you have connected your sensor to watch. 

Im still testing juggluco but for me my setup is now best of what Ive tested.... I tried to use xdrip only but I cant run watch+sensor in standalone mode... it just wont connect 
maybe juggluca can receive data from gdh or xdrip then upload to LibreView

**Comment by pachi81** [comment]
I don´t think, gdh or xdrip can send to Juggluco. But if you receive the values with Juggluco on watch it will forward to phone.
The most important settings in Juggluco on phone is to do not send values immediately to LibreView.

Just a question, I need Juggluco on phone to start the sensor, this will not work on watch!?
Or are you using Libre 2 mainly with xDrip?

**Comment by oblus** [comment]
Im always starting sensor with Libre app in phone and after a hour warmup i scan once with Libre, then open juggluco on phone, scan once then connect to watch and get reading on watch from phone. In this moment I have sensor details on juggluco wear app so I reconnect to sensor stright to juggluco wear, then broadcast to gdh and gdh on phone broadcast to xdrip. I can now disable juggluco and libre on phone. What annoys me is need to scan at time to time by Libre app to send some data to LibreView...

xdrip have more readable interface for me and I can use calibrations, easily export data to pdf... etc.

**Comment by froster82** [comment]
@oblus, you already have everything you need. Juggluco is your answer.
My setup is as follows: 1. I always activate my sensors with Juggluco on the phone. 2. Juggluco on the phone is connected to my primary account on Libreview, and sends all the data to LV. 3. I also have a WearOS watch and use it together with the phone version (I also use direct sensor-watch connection). 4. For statistical purposes and for Abbot needs (complaints) I also have my LibreLink app (in Poland it is called LibreLink, but in other places it might be just Libre app), but it is connected to my second account, and I scan the sensor a couple of times just to have some data there. 
Everything else happens in Juggluco. Do not disable Juggluco on the phone, enable "Send to Libreview", and "Immediately" options in Libreview menu. If you want, you can also broadcast data straight from Juggluco do xDrip. This way you phone will take over the burden of power consumption, and the watch will last some longer.

**Comment by pachi81** [comment]
> Do not disable Juggluco on the phone, enable "Send to Libreview", and "Immediately" options in Libreview menu.

Just one remark, "Immediately" should only be enabled, if you have a follower app, which needs to receive the values in time.
Otherwise it will save battery usage, if you do not send any single value to LibreView, it is enough to send them as packet from time to time.

As my app is a follower app and the upload to the servers should be done by the apps connected to the sensors, I will close this enhancement.
