### ISSUE TITLE
No values on Samsung watch for almost a week

### ISSUE THREAD

**Issue by FlorisQK** [pachi81/GlucoDataHandler#185]
GlucoseDataHandler was working fine for months.
(sometimes an error but always back on after restarting the watch)
But now since last Weddnesday not getting any values anymore.

Getting different errors:
when I restart my watch
first LinbrerLinkUp error 2:not authenticated 
then LibreLinkUp error (just general)
then LibreLinkUP 429 error (the most)

I tried reconnecting with LibreLinkup, reset connection within DataGlucoseHandler app, restarting the watch, leaving it off for a while etc. etc.
Would love to have this back on my watch because it makes daily life easier.
Anyone a suggestion how to fix this or another solution.
Thanks for any help in advance.

**Comment by pachi81** [comment]
Hi,
it seems Abbott did some more changes to their servers and blocks too many requests (429).
So it is important to use only one follower app for your account! Please stop or uninstall LibreLinkUp app.
Also stop the source in GDH for some minutes.
If you have several devices, following the same account, please check to disable them or use different accounts.
Please also stop the data source in watch version as it is not needed, if you already receive the data in phone version.

Regards, Michael

**Comment by FlorisQK** [comment]
> Hi, it seems Abbott did some more changes to their servers and blocks too many requests (429). So it is important to use only one follower app for your account! Please stop or uninstall LibreLinkUp app. Also stop the source in GDH for some minutes. If you have several devices, following the same account, please check to disable them or use different accounts. Please also stop the data source in watch version as it is not needed, if you already receive the data in phone version.
> 
> Regards, Michael

Thanks. No luck yet but I keep trying and let you know. Now only running GDH on my watch.

**Comment by FlorisQK** [comment]
Still working so looking for other solutions. Thanks. And maybe I can ask abbott about the 429..

**Comment by pachi81** [comment]
Abbott will not support 3rd party apps.
What about LibreLinkUp? Is this app working?

**Comment by FlorisQK** [comment]
yes LibreLinkUp app is working. (Has always been working. Did a reinstall with a new login just to try if this helps with the 429).

**Comment by pachi81** [comment]
Are you have always used LibreLinkUp App?

**Comment by FlorisQK** [comment]
yes always. thanks

**Comment by pachi81** [comment]
> Hi, it seems Abbott did some more changes to their servers and blocks too many requests (429). So it is important to use only one follower app for your account! Please stop or uninstall LibreLinkUp app. Also stop the source in GDH for some minutes. If you have several devices, following the same account, please check to disable them or use different accounts. Please also stop the data source in watch version as it is not needed, if you already receive the data in phone version.
> 
> Regards, Michael

Have you red this???

**Comment by FlorisQK** [comment]
yes and tried all. made a whole new account and only used GDH on phone with it. But no luck.

**Comment by pachi81** [comment]
Maybe it is not related to the account, but to the device...
Please completely stop the LibreLinkUp app for at least an hour and set the interval to 5 minutes in GDH...

**Comment by FlorisQK** [comment]
Thanks will try this later. (need to find the right moment). I'll let you know.

**Comment by pachi81** [comment]
Close it as it is not an issue of GDH.

**Comment by FlorisQK** [comment]
yeah sorry tried all not able to solve, thanks for your help anyway

**Comment by FlorisQK** [comment]
thanks maybe I try during the holidays but you can close the issue here..thanks
