### ISSUE TITLE
Be kind with non-tech people

### ISSUE THREAD

**Issue by psonnera** [pachi81/GlucoDataHandler#33]
This is a great app, can you put more screenshots of the app, various configuration menus etc. for non tech people?
Thanks!

**Comment by pachi81** [comment]
Hi,
I know the docu is not my main topic 😉
This App does not have a lot of configurations, it still provides Wear OS Complications, which are part of many watchfaces.
The Tasker integration is not needed for that. Tasker can be used for automations, but this is not such easy.

Or what especcialy you are meaning?

Regards, Michael

**Comment by psonnera** [comment]
Let me try to find time to do something and show you what I mean. The product is good, just that following the instructions can be conplex for some. Will PR when done. Thanks!

**Comment by pachi81** [comment]
Hi, 

I have checked your docu and it looks really good. I know, I have to add some more docu, but starting with your changes is great:
https://github.com/pachi81/GlucoDataHandler/pull/39

Can you have a look?

**Comment by psonnera** [comment]
I will try to take better screenshots this weekend. Thanks!

**Comment by pachi81** [comment]
Thank you! But you don't have to. It should be my task writing the docu 😀

**Comment by pachi81** [comment]
Thank you for your input. I close this issue.
