### ISSUE TITLE
Glucodata seems incompatible with xDrip and AndroidAPS

### ISSUE THREAD

**Issue by TheFlyingDave** [pachi81/GlucoDataHandler#87]
I use xDrip+ with AndroidAPS and am trying to get GlucoDataHandler working for a custom watchface.

I followed the instructions and set "Identify receiver" in xDrip+ to empty (was info.nightscout.androidaps).
Now the GlucoData app receives xDrip broadcasts but they are not getting to AndroidAPS. I have "Send glucodata broadcast" enabled and have tried it both with AndroidAPS checked and unchecked in "Identify Receiver". In both cases AndroidAPS never gets updated glucose values.
TIA

**Comment by pachi81** [comment]
Please try for Identify receiver:
`info.nightscout.androidaps
de.michelinside.glucodatahandler`

**Comment by TheFlyingDave** [comment]
That worked. Many thanks!

**Comment by TheFlyingDave** [comment]
THis can be closed.

**Comment by pachi81** [comment]
Thank you for the feedback! If I have some time, I will update the Readme...
