### ISSUE TITLE
Pixel 8 Pro can't install

### ISSUE THREAD

**Issue by ChrisJSLH** [pachi81/GlucoDataHandler#98]
Hi, I can't install on Pixel 8 Pro. Says device isn't compatible.

**Comment by pachi81** [comment]
Hi, which firmware version?
Maybe I have to increase the maximum supported version.
I have to check. Hopefully no deprecated or removed function, then it can take some more time.

**Comment by pachi81** [comment]
I have red, that it should work also on Android 14.
Can you try to install using adb?

**Comment by ChrisJSLH** [comment]
It works on Android 14 for sure. I had it installed on my Pixel 7 before and after the upgrade to Android 14 and no problems. Although only installed it on Android 13 before the upgrade.

The exact message is "App not installed as app isn't compatible with your phone".

**Comment by pachi81** [comment]
I also expect that it should be working in Android 14. I have red in the docu, that Android 14 supports app with a target SDK of 23 and my app uses target SDK 33. 
If possible, please try to install it using adb from a computer:
`adb install -r -g GlucoDataHandler_0.9.6.apk`

I hope that adb will offer a better error message. 

Or you can try the fix of this video:
https://www.youtube.com/watch?v=ZYx9NEi1t2c
(Have you disabled Play Protect already?)

**Comment by pachi81** [comment]
Hi, 
any news? Did you get it to work or do you have still the problem?

**Comment by ChrisJSLH** [comment]
Still no joy. I can't get it to install from the phone and when I try and push it from adb it complains about a missing wear dependency. (This may be due to me not having the full SDK installed, just minimal ADB).On 18 Oct 2023 08:34, pachi81 ***@***.***> wrote:
Hi,
any news? Did you get it to work or do you have still the problem?

**Comment by pachi81** [comment]
Can you post the whole adb error message. Have you tried to disable Play Protect?

**Comment by ChrisJSLH** [comment]
I'll send the full adb error message later when I'm at home. Yes, definitely tried to disable Play Protect.On 18 Oct 2023 11:28, pachi81 ***@***.***> wrote:
Can you post the whole adb error message. Have you tried to disable Play Protect?

**Comment by ChrisJSLH** [comment]
ADB Error Message:
Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package de.michelinside.glucodatahandler requires unavailable shared library com.google.android.wearable; failing!]

 

Yes, definitely trying to install the Wear version.

**Comment by pachi81** [comment]
You try to install the wear version on mobile?
That is not possible, you have to use the version without wear.

**Comment by ChrisJSLH** [comment]
Omg. I was getting confused with G-Watch Wear App which has Wear version and a Tizen version. What an idiot I am...On 18 Oct 2023 19:13, pachi81 ***@***.***> wrote:
You try to install the wear version on mobile?
That is not possible, you have to use the version without wear.

**Comment by pachi81** [comment]
😁
No problem, it happend to me, too...🤣

**Comment by pachi81** [comment]
Close it as solved.
